class TextAnalyticsPage {

  final Map<String, Map<String, String>> strings = {
    'english': {
      'T00': 'January',
      'T01': 'February',
      'T02': 'March',
      'T03': 'April',
      'T04': 'May',
      'T05': 'June',
      'T06': 'July',
      'T07': 'August',
      'T08': 'September',
      'T09': 'October',
      'T10': 'November',
      'T11': 'December',
      'T12': 'Analytics',
      'T13': 'View transactions',
      'T14': 'Total: ',
      'T15': 'Maximum: ',
      'T16': 'Minimum: ',
      'T17': 'Average: ',
      'T18': 'Create new card',
    },
    'russian': {
      'T00': 'Январь',
      'T01': 'Февраль',
      'T02': 'Март',
      'T03': 'Апрель',
      'T04': 'Май',
      'T05': 'Июнь',
      'T06': 'Июль',
      'T07': 'Август',
      'T08': 'Сентябрь',
      'T09': 'Октябрь',
      'T10': 'Ноябрь',
      'T11': 'Декабрь',
      'T12': 'Аналитика',
      'T13': 'Открыть транзакции',
      'T14': 'Итого: ',
      'T15': 'Максимум: ',
      'T16': 'Минимум: ',
      'T17': 'В среднем: ',
      'T18': 'Создайте новую карту',
    },
    'german': {
      'T00': 'Januar',
      'T01': 'Februar',
      'T02': 'März',
      'T03': 'April',
      'T04': 'Kann',
      'T05': 'Juni',
      'T06': 'Juli',
      'T07': 'August',
      'T08': 'September',
      'T09': 'Oktober',
      'T10': 'November',
      'T11': 'Dezember',
      'T12': 'Analytik',
      'T13': 'Transaktionen anzeigen',
      'T14': 'Gesamt: ',
      'T15': 'Maximal: ',
      'T16': 'Minimum: ',
      'T17': 'Durchschnittlich: ',
      'T18': 'Neue Karte erstellen',
    },
    'japanese': {
      'T00': '1月',
      'T01': '2月',
      'T02': '3月',
      'T03': '4月',
      'T04': '5月',
      'T05': '6月',
      'T06': '7月',
      'T07': '8月',
      'T08': '9月',
      'T09': '10月',
      'T10': '11月',
      'T11': '12月',
      'T12': '分析',
      'T13': 'トランザクションを表示する',
      'T14': '合計： ',
      'T15': '最大: ',
      'T16': '最小: ',
      'T17': '平均: ',
      'T18': '新しいカードを作成する',
    },
    'italian': {
      'T00': 'Gennaio',
      'T01': 'Febbraio',
      'T02': 'Marzo',
      'T03': 'Aprile',
      'T04': 'Maggio',
      'T05': 'Giugno',
      'T06': 'Luglio',
      'T07': 'Agosto',
      'T08': 'Settembre',
      'T09': 'Ottobre',
      'T10': 'Novembre',
      'T11': 'Dicembre',
      'T12': 'Analytics',
      'T13': 'Visualizza le transazioni',
      'T14': 'Totale: ',
      'T15': 'Massimo: ',
      'T16': 'Minimo: ',
      'T17': 'Media: ',
      'T18': 'Crea nuova carta',
    },
    'french': {
      'T00': 'Janvier',
      'T01': 'Février',
      'T02': 'Mars',
      'T03': 'Avril',
      'T04': 'Mai',
      'T05': 'Juin',
      'T06': 'Juillet',
      'T07': 'Août',
      'T08': 'Septembre',
      'T09': 'Octobre',
      'T10': 'Novembre',
      'T11': 'Décembre',
      'T12': 'Analytique',
      'T13': 'Voir les transactions',
      'T14': 'Total: ',
      'T15': 'Maximum: ',
      'T16': 'Minimum: ',
      'T17': 'Moyenne: ',
      'T18': 'Créer une nouvelle carte',
    },
    'spanish': {
      'T00': 'Enero',
      'T01': 'Febrero',
      'T02': 'Marzo',
      'T03': 'Abril',
      'T04': 'Mayo',
      'T05': 'Junio',
      'T06': 'Julio',
      'T07': 'Agosto',
      'T08': 'Septiembre',
      'T09': 'Octubre',
      'T10': 'Noviembre',
      'T11': 'Diciembre',
      'T12': 'Analítica',
      'T13': 'Ver transacciones',
      'T14': 'Total: ',
      'T15': 'Máximo: ',
      'T16': 'Mínimo: ',
      'T17': 'Promedio: ',
      'T18': 'Crear nueva tarjeta',
    },
    'korean': {
      'T00': '일월',
      'T01': '이월',
      'T02': '행진',
      'T03': '사월',
      'T04': '오월',
      'T05': '유월',
      'T06': '칠월',
      'T07': '팔월',
      'T08': '구월',
      'T09': '십월',
      'T10': '십일월',
      'T11': '십이 월',
      'T12': '해석학',
      'T13': '거래보기',
      'T14': '합계: ',
      'T15': '최고: ',
      'T16': '최저한의: ',
      'T17': '평균: ',
      'T18': '새 카드 만들기',
    },
  };

}