class TextEditor {

  final Map<String, Map<String, String>> strings = {
    'english': {
      'T00': 'Successfully uploaded!',
      'T01': 'Upload failed!',
      'T02': 'Ok',
      'T03': 'Successfully deleted!',
      'T04': 'Deletion failed!',
      'T05': 'Confidential',
      'T06': 'Opened',
      'T07': 'Apply',
      'T08': 'Upload',
      'T09': 'Upload card?',
      'T10': 'Please make sure that you do not share sensitive information that could harm you or others',
      'T11': 'Cancel',
      'T12': 'Please check internet connection or try again later',
      'T13': 'Editor',
      'T14': 'Do you really want to delete card?',
      'T15': 'Delete',
      'T16': 'Signature',
      'T17': 'Done',
      'T18': 'Edit',
      'T19': 'Title',
      'T20': 'Add field',
      'T21': 'Tap to edit',
      'T22': 'Edit the field',
      'T23': 'Description',
      'T24': 'Card type',
      'T25': 'Please note that this attribute cannot be changed after uploading the card',
      'T26': 'For more information address the help page',
    },
    'russian': {
      'T00': 'Успешно загружено!',
      'T01': 'Загрузка не удалась!',
      'T02': 'Ok',
      'T03': 'Успешно удалено!',
      'T04': 'Удалить не удалось!',
      'T05': 'Конфедициальная',
      'T06': 'Открытая',
      'T07': 'Применить',
      'T08': 'Загрузить',
      'T09': 'Загрузить карточку?',
      'T10': 'Пожалуйста, убедитесь, что вы не передаете чувствительную информацию способную причинить вред вам или другим лицам',
      'T11': 'Отмена',
      'T12': 'Пожалуйста, проверьте подключение к интернету или попробуйте еще раз позднее',
      'T13': 'Редактор',
      'T14': 'Вы действительно желаете удалить данную карточку?',
      'T15': 'Удалить',
      'T16': 'Подпись',
      'T17': 'Готово',
      'T18': 'Отредактировать',
      'T19': 'Заголовок',
      'T20': 'Добавить поле',
      'T21': 'Нажмите, чтобы отредактировать поле',
      'T22': 'Отредактируйте поле',
      'T23': 'Описание',
      'T24': 'Тип карты',
      'T25': 'Пожалуйста, обратите внимание, что данный параметр нельзя будет изменить после того, как вы загрузите карточку',
      'T26': 'Для получения дополнительной информации обратитесь на страницу справки',
    },
    'german': {
      'T00': 'Erfolgreich hochgeladen!',
      'T01': 'Upload fehlgeschlagen!',
      'T02': 'Ok',
      'T03': 'Erfolgreich gelöscht!',
      'T04': 'Löschen fehlgeschlagen!',
      'T05': 'Geheim',
      'T06': 'Geöffnet',
      'T07': 'Anwenden',
      'T08': 'Hochladen',
      'T09': 'Karte hochladen?',
      'T10': 'Bitte stellen Sie sicher, dass Sie keine vertraulichen Informationen weitergeben, die Ihnen oder anderen schaden könnten',
      'T11': 'Cancel',
      'T12': 'Bitte überprüfen Sie die Internetverbindung oder versuchen Sie es später erneut',
      'T13': 'Editor',
      'T14': 'Möchten Sie die Karte wirklich löschen?',
      'T15': 'Löschen',
      'T16': 'Unterschrift',
      'T17': 'Erledigt',
      'T18': 'Bearbeiten',
      'T19': 'Titel',
      'T20': 'Feld hinzufügen',
      'T21': 'Tippen Sie zum Bearbeiten auf',
      'T22': 'Bearbeiten Sie das Feld',
      'T23': 'Beschreibung',
      'T24': 'Kartentyp',
      'T25': 'Bitte beachten Sie, dass dieses Attribut nach dem Hochladen der Karte nicht mehr geändert werden kann',
      'T26': 'Weitere Informationen finden Sie auf der Hilfeseite',
    },
    'japanese': {
      'T00': '正常にアップロードされました！',
      'T01': 'アップロードに失敗しました！',
      'T02': 'Ok',
      'T03': '正常に削除されました！',
      'T04': '削除に失敗しました！',
      'T05': '機密',
      'T06': 'オープン',
      'T07': '適用する',
      'T08': 'アップロード',
      'T09': 'カードをアップロードしますか？',
      'T10': '自分や他人に危害を加える可能性のある機密情報を共有しないようにしてください',
      'T11': 'キャンセル',
      'T12': 'インターネット接続を確認するか、後でもう一度お試しください',
      'T13': '編集者',
      'T14': '本当にカードを削除しますか？',
      'T15': '削除',
      'T16': '署名',
      'T17': '完了',
      'T18': '編集',
      'T19': '題名',
      'T20': 'フィールドを追加',
      'T21': 'タップして編集',
      'T22': 'フィールドを編集する',
      'T23': '説明',
      'T24': 'カードの種類',
      'T25': 'カードのアップロード後にこの属性を変更することはできませんのでご注意ください',
      'T26': '詳細については、ヘルプページを参照してください',
    },
    'italian': {
      'T00': 'Caricato con successo!',
      'T01': 'Caricamento fallito!',
      'T02': 'Ok',
      'T03': 'Eliminato con successo!',
      'T04': 'Eliminazione non riuscita!',
      'T05': 'Riservata',
      'T06': 'Ha aperto',
      'T07': 'Applicare',
      'T08': 'Caricare',
      'T09': 'Caricare la carta?',
      'T10': 'Assicurati di non condividere informazioni sensibili che potrebbero danneggiare te o altri',
      'T11': 'Annulla',
      'T12': 'Verifica la connessione a Internet o riprova più tardi',
      'T13': 'Editor',
      'T14': 'Vuoi davvero eliminare la carta?',
      'T15': 'Elimina',
      'T16': 'Firma',
      'T17': 'Fatto',
      'T18': 'Modificare',
      'T19': 'Titolo',
      'T20': 'Aggiungi campo',
      'T21': 'Tocca per modificare',
      'T22': 'Modifica il campo',
      'T23': 'Descrizione',
      'T24': 'Tipo di carta',
      'T25': 'Tieni presente che questo attributo non può essere modificato dopo aver caricato la carta',
      'T26': 'Per ulteriori informazioni, consultare la pagina della guida',
    },
    'french': {
      'T00': 'Importé avec succès!',
      'T01': 'Le téléchargement a échoué!',
      'T02': 'Ok',
      'T03': 'Supprimé avec succès!',
      'T04': 'La suppression a échoué!',
      'T05': 'Confidentielle',
      'T06': 'Ouverte',
      'T07': 'Appliquer',
      'T08': 'Télécharger',
      'T09': 'Télécharger la carte?',
      'T10': 'Veuillez vous assurer de ne pas partager d\'informations sensibles qui pourraient nuire à vous ou à d\'autres',
      'T11': 'Annuler',
      'T12': 'Veuillez vérifier la connexion Internet ou réessayer plus tard',
      'T13': 'Éditeur',
      'T14': 'Voulez-vous vraiment supprimer la carte?',
      'T15': 'Supprimer',
      'T16': 'Signature',
      'T17': 'Terminé',
      'T18': 'Éditer',
      'T19': 'Titre',
      'T20': 'Ajouter le champ',
      'T21': 'Appuyez pour modifier',
      'T22': 'Modifier le champ',
      'T23': 'La description',
      'T24': 'Type de carte',
      'T25': 'Veuillez noter que cet attribut ne peut pas être modifié après le téléchargement de la carte',
      'T26': 'Pour plus d\'informations, consultez la page d\'aide',
    },
    'spanish': {
      'T00': '¡Cargado correctamente!',
      'T01': '¡Subida fallida!',
      'T02': 'Ok',
      'T03': 'Eliminado con éxito!',
      'T04': '¡Error al borrar!',
      'T05': 'Confidencial',
      'T06': 'Abierta',
      'T07': 'Aplicar',
      'T08': 'Subir',
      'T09': '¿Subir tarjeta?',
      'T10': 'Asegúrese de no compartir información confidencial que pueda dañarlo a usted oa otras personas',
      'T11': 'Cancelar',
      'T12': 'Comprueba la conexión a Internet o vuelve a intentarlo más tarde',
      'T13': 'Editor',
      'T14': '¿Realmente quieres borrar la tarjeta?',
      'T15': 'Eliminar',
      'T16': 'Firma',
      'T17': 'Hecho',
      'T18': 'Editar',
      'T19': 'Título',
      'T20': 'Agregue campo',
      'T21': 'Pulsa para editar',
      'T22': 'Edita el campo',
      'T23': 'Descripción',
      'T24': 'Tipo de tarjeta',
      'T25': 'Tenga en cuenta que este atributo no se puede cambiar después de cargar la tarjeta',
      'T26': 'Para obtener más información, diríjase a la página de ayuda',
    },
    'korean': {
      'T00': '성공적으로 업로드되었습니다!',
      'T01': '업로드 실패!',
      'T02': 'Ok',
      'T03': '성공적으로 삭제되었습니다!',
      'T04': '삭제하지 못했습니다!',
      'T05': '기밀',
      'T06': '개장',
      'T07': '대다',
      'T08': '업로드',
      'T09': '카드를 업로드 하시겠습니까?',
      'T10': '본인 또는 타인에게 해를 끼칠 수있는 민감한 정보를 공유하지 않도록하십시오',
      'T11': '취소',
      'T12': '인터넷 연결을 확인하거나 나중에 다시 시도하십시오',
      'T13': '편집자',
      'T14': '카드를 정말로 삭제 하시겠습니까?',
      'T15': '지우다',
      'T16': '서명',
      'T17': '끝난',
      'T18': '편집하다',
      'T19': '표제',
      'T20': '필드 추가',
      'T21': '수정하려면 탭하세요',
      'T22': '필드 편집',
      'T23': '기술',
      'T24': '카드 종류',
      'T25': '카드를 업로드 한 후에는이 속성을 변경할 수 없습니다',
      'T26': '자세한 내용은 도움말 페이지를 참조하십시오',
    },
  };
}