class TextTermsAndPolicyPage {

  final Map<String, Map<String, String>> strings = {
    'english': {
      'T00': 'Are you absolutely sure that you want to delete your account and lose access to all the content you have accumulated, as well as the ability to edit or delete your personal information that may remain in the collections of other users?',
      'T01': 'Terms and Policies',
      'T02': 'Please check your internet connection and try again',
      'T03': 'Revoke your consent and delete account',
      'T04': 'Deleting account',
      'T05': 'Cancel',
      'T06': 'Delete',
      'T07': 'Please enter your password to confirm the action',
    },
    'russian': {
      'T00': 'Вы абсолютно уверены, что хотите удалить свою учетную запись и потерять доступ ко всему накопленному вами контенту, а также возможность редактировать или удалять вашу личную информацию, которая может остаться в коллекциях других пользователей?',
      'T01': 'Условия и политика',
      'T02': 'Пожалуйста, проверьте ваше интернет-соединение и попробуйте еще раз',
      'T03': 'Отозвать свое согласие и удалить аккаунт',
      'T04': 'Удаление аккаунта',
      'T05': 'Отмена',
      'T06': 'Удалить',
      'T07': 'Пожалуйста, введите свой пароль, чтобы подтвердить действие',
    },
    'german': {
      'T00': 'Sind Sie absolut sicher, dass Sie Ihr Konto löschen und den Zugriff auf alle von Ihnen gesammelten Inhalte sowie die Möglichkeit zum Bearbeiten oder Löschen Ihrer persönlichen Informationen verlieren möchten, die möglicherweise in den Sammlungen anderer Benutzer verbleiben?',
      'T01': 'Nutzungsbedingungen und Richtlinien',
      'T02': 'Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut',
      'T03': 'Widerrufen Sie Ihre Einwilligung und löschen Sie das Konto',
      'T04': 'Konto löschen',
      'T05': 'Stornieren',
      'T06': 'Löschen',
      'T07': 'Bitte geben Sie Ihr Passwort ein, um die Aktion zu bestätigen',
    },
    'japanese': {
      'T00': 'アカウントを削除して、蓄積したすべてのコンテンツにアクセスできなくなったり、他のユーザーのコレクションに残っている可能性のある個人情報を編集または削除したりすることを絶対に確信していますか？',
      'T01': '利用規約とポリシー',
      'T02': 'インターネット接続を確認して、もう一度お試しください',
      'T03': '同意を取り消してアカウントを削除する',
      'T04': 'アカウントを削除しています',
      'T05': 'キャンセル',
      'T06': '削除',
      'T07': 'アクションを確認するためにパスワードを入力してください',
    },
    'italian': {
      'T00': 'Sei assolutamente sicuro di voler eliminare il tuo account e perdere l\'accesso a tutti i contenuti che hai accumulato, oltre alla possibilità di modificare o cancellare le tue informazioni personali che potrebbero rimanere nelle raccolte di altri utenti?',
      'T01': 'Termini e politiche',
      'T02': 'Controlla la tua connessione Internet e riprova',
      'T03': 'Revoca il tuo consenso ed elimina l\'account',
      'T04': 'Eliminazione dell\'account',
      'T05': 'Annulla',
      'T06': 'Elimina',
      'T07': 'Inserisci la tua password per confermare l\'azione',
    },
    'french': {
      'T00': 'Êtes-vous absolument sûr de vouloir supprimer votre compte et perdre l\'accès à tout le contenu que vous avez accumulé, ainsi que la possibilité de modifier ou de supprimer vos informations personnelles qui peuvent rester dans les collections d\'autres utilisateurs?',
      'T01': 'Termes et politiques',
      'T02': 'S\'il vous plaît, vérifiez votre connexion à internet et réessayez',
      'T03': 'Révoquer votre consentement et supprimer le compte',
      'T04': 'Suppression du compte',
      'T05': 'Annuler',
      'T06': 'Supprimer',
      'T07': 'Veuillez saisir votre mot de passe pour confirmer l\'action',
    },
    'spanish': {
      'T00': '¿Está absolutamente seguro de que desea eliminar su cuenta y perder el acceso a todo el contenido que ha acumulado, así como la posibilidad de editar o eliminar su información personal que puede permanecer en las colecciones de otros usuarios?',
      'T01': 'Términos y Políticas',
      'T02': 'Comprueba tu conexión a Internet y vuelve a intentarlo',
      'T03': 'Revocar su consentimiento y eliminar cuenta',
      'T04': 'Eliminando cuenta',
      'T05': 'Cancelar',
      'T06': 'Eliminar',
      'T07': 'Ingrese su contraseña para confirmar la acción',
    },
    'korean': {
      'T00': '계정을 삭제하고 축적 한 모든 콘텐츠에 대한 액세스 권한을 잃고 다른 사용자의 컬렉션에 남아있을 수있는 개인 정보를 편집하거나 삭제할 수있는 권한을 잃기를 원하십니까?',
      'T01': '약관 및 정책',
      'T02': '인터넷 연결을 확인하고 다시 시도하십시오',
      'T03': '동의 철회 및 계정 삭제',
      'T04': '계정 삭제',
      'T05': '취소',
      'T06': '지우다',
      'T07': '작업을 확인하려면 암호를 입력하십시오',
    },
  };

}