class TextPublicViewerLoader {

  final Map<String, Map<String, String>> strings = {
    'english': {
      'T00': 'Could not load the data',
      'T01': 'Card has been deleted by its owner',
      'T02': 'You are denied access to the card by its owner',
      'T03': 'Delete',
      'T04': 'Ok',
      'T05': 'Please check internet connection or try again later',
      'T06': 'Back',
      'T07': 'Retry',
    },
    'russian': {
      'T00': 'Не удалось загрузить данные',
      'T01': 'Карточка была удалена владельцем',
      'T02': 'Вам отказано в доступе к карте ее владельцем',
      'T03': 'Удалить',
      'T04': 'Ok',
      'T05': 'Пожалуйста, проверьте подключение к интернету или попробуйте еще раз позднее',
      'T06': 'Назад',
      'T07': 'Повтор',
    },
    'german': {
      'T00': 'Die Daten konnten nicht geladen werden',
      'T01': 'Die Karte wurde von ihrem Besitzer gelöscht',
      'T02': 'Der Eigentümer verweigert Ihnen den Zugriff auf die Karte',
      'T03': 'Löschen',
      'T04': 'Ok',
      'T05': 'Bitte überprüfen Sie die Internetverbindung oder versuchen Sie es später erneut',
      'T06': 'Zurück',
      'T07': 'Wiederholen',
    },
    'japanese': {
      'T00': 'データを読み込めませんでした',
      'T01': 'カードは所有者によって削除されました',
      'T02': 'あなたはその所有者によってカードへのアクセスを拒否されています',
      'T03': '削除',
      'T04': 'Ok',
      'T05': 'インターネット接続を確認するか、後でもう一度お試しください',
      'T06': '裏面',
      'T07': 'リトライ',
    },
    'italian': {
      'T00': 'Impossibile caricare i dati',
      'T01': 'La carta è stata eliminata dal suo proprietario',
      'T02': 'Ti viene negato l\'accesso alla carta dal suo proprietario',
      'T03': 'Elimina',
      'T04': 'Ok',
      'T05': 'Verifica la connessione a Internet o riprova più tardi',
      'T06': 'Indietro',
      'T07': 'Riprova',
    },
    'french': {
      'T00': 'Impossible de charger les données',
      'T01': 'La carte a été supprimée par son propriétaire',
      'T02': 'L\'accès à la carte vous est refusé par son propriétaire',
      'T03': 'Supprimer',
      'T04': 'Ok',
      'T05': 'Veuillez vérifier la connexion Internet ou réessayer plus tard',
      'T06': 'Retour',
      'T07': 'Réessayez',
    },
    'spanish': {
      'T00': 'No se pudieron cargar los datos',
      'T01': 'Tarjeta ha sido eliminada por su dueño',
      'T02': 'Su propietario le niega el acceso a la tarjeta',
      'T03': 'Eliminar',
      'T04': 'Ok',
      'T05': 'Comprueba la conexión a Internet o vuelve a intentarlo más tarde',
      'T06': 'Atrás',
      'T07': 'Rever',
    },
    'korean': {
      'T00': '데이터를로드 할 수 없습니다',
      'T01': '소유자가 카드를 삭제했습니다',
      'T02': '소유자가 카드에 대한 액세스를 거부했습니다',
      'T03': '지우다',
      'T04': 'Ok',
      'T05': '인터넷 연결을 확인하거나 나중에 다시 시도하십시오',
      'T06': '뒤',
      'T07': '다시 해 보다',
    },
  };

}