class TextShareModule {

  final Map<String, Map<String, String>> strings = {
    'english': {
      'T00': 'Share',
      'T01': 'The device does not support this data transfer method',
      'T02': 'Copied to clipboard',
      'T03': 'NFC module is inactive',
      'T04': 'Enable NFC module',
      'T05': 'NFC support will be added soon. Until then, please use the QR-code or the link',
      'T06': 'NFC module is unavailable',
      'T07': 'Back',
    },
    'russian': {
      'T00': 'Поделиться',
      'T01': 'Устройство не поддерживает данный метод передачи данных',
      'T02': 'Скопированно в буфер обмена',
      'T03': 'Модуль NFC активен',
      'T04': 'Включить модуль NFC',
      'T05': 'Поддержка NFC будет добавлена скоро. А пока, пожалуйста, используйте QR-код или ссылку',
      'T06': 'Модуль NFC недоступен',
      'T07': 'Назад',
    },
    'german': {
      'T00': 'Teilen',
      'T01': 'Das Gerät unterstützt diese Datenübertragungsmethode nicht',
      'T02': 'In die Zwischenablage kopiert',
      'T03': 'Das NFC-Modul ist inaktiv',
      'T04': 'Aktivieren Sie das NFC-Modul',
      'T05': 'NFC-Unterstützung wird in Kürze hinzugefügt. Bis dahin benutzen Sie bitte den QR-Code oder den Link',
      'T06': 'NFC-Modul ist nicht verfügbar',
      'T07': 'Zurück',
    },
    'japanese': {
      'T00': 'シェア',
      'T01': 'デバイスはこのデータ転送方法をサポートしていません',
      'T02': 'クリップボードにコピー',
      'T03': 'NFCモジュールは非アクティブです',
      'T04': 'NFCモジュールを有効にする',
      'T05': 'NFCサポートはまもなく追加されます。 それまでは、QRコードまたはリンクをご利用ください',
      'T06': 'NFCモジュールは利用できません',
      'T07': '裏面',
    },
    'italian': {
      'T00': 'Condividere',
      'T01': 'Il dispositivo non supporta questo metodo di trasferimento dati',
      'T02': 'Copiato negli appunti',
      'T03': 'Il modulo NFC è inattivo',
      'T04': 'Abilita modulo NFC',
      'T05': 'Presto verrà aggiunto il supporto NFC. Fino ad allora, utilizza il codice QR o il link',
      'T06': 'Il modulo NFC non è disponibile',
      'T07': 'Indietro',
    },
    'french': {
      'T00': 'Partager',
      'T01': 'L\'appareil ne prend pas en charge cette méthode de transfert de données',
      'T02': 'Copié dans le presse-papier',
      'T03': 'Le module NFC est inactif',
      'T04': 'Activer le module NFC',
      'T05': 'Le support NFC sera bientôt ajouté. D\'ici là, veuillez utiliser le code QR ou le lien',
      'T06': 'Le module NFC n\'est pas disponible',
      'T07': 'Retour',
    },
    'spanish': {
      'T00': 'Compartir',
      'T01': 'El dispositivo no admite este método de transferencia de datos',
      'T02': 'Copiada al portapapeles',
      'T03': 'El módulo NFC está inactivo',
      'T04': 'Habilitar el módulo NFC',
      'T05': 'La compatibilidad con NFC se agregará pronto. Hasta entonces, utilice el código QR o el enlace',
      'T06': 'El módulo NFC no está disponible',
      'T07': 'Atrás',
    },
    'korean': {
      'T00': '공유',
      'T01': '장치가이 데이터 전송 방법을 지원하지 않습니다',
      'T02': '클립 보드에 복사 됨',
      'T03': 'NFC 모듈이 비활성화되었습니다',
      'T04': 'NFC 모듈 활성화',
      'T05': 'NFC 지원이 곧 추가 될 예정입니다. 그때까지는 QR 코드 또는 링크를 사용하십시오',
      'T06': 'NFC 모듈을 사용할 수 없습니다',
      'T07': '뒤',
    },
  };

}