class TextHomePageCollection {

  final Map<String, Map<String, String>> strings = {
    'english': {
      'T00': 'Do you really want to delete selected cards? ',
      'T01': 'Cancel',
      'T02': 'Delete',
      'T03': 'Search...',
      'T04': 'Collection',
      'T05': 'Deselect',
      'T06': 'Select all',
      'T07': 'Main',
      'T08': 'Favorites',
      'T09': 'Archive',
      'T10': 'Loading...',
      'T11': 'Move to Favorites',
      'T12': 'Move to Archive',
      'T13': 'Private card can be shared only by its owner',
      'T14': 'Ok',
      'T15': 'This collection is empty',
      'T16': 'The search gave no results',
      'T17': 'Move to Main',
    },
    'russian': {
      'T00': 'Вы действительно желаете удалить выбранные карточки? ',
      'T01': 'Отмена',
      'T02': 'Удалить',
      'T03': 'Поиск...',
      'T04': 'Коллекция',
      'T05': 'Снять выбор',
      'T06': 'Выбрать все',
      'T07': 'Основное',
      'T08': 'Избранное',
      'T09': 'Архив',
      'T10': 'Загрузка...',
      'T11': 'Переместить в Избранное',
      'T12': 'Переместить в Архив',
      'T13': 'Поделиться конфедициальной карточкой может только владелец',
      'T14': 'Ok',
      'T15': 'Данная коллекция пуста',
      'T16': 'Поиск не дал результатов',
      'T17': 'Переместить в Основное',
    },
    'german': {
      'T00': 'Möchten Sie wirklich ausgewählte Karten löschen? ',
      'T01': 'Stornieren',
      'T02': 'Löschen',
      'T03': 'Suche...',
      'T04': 'Sammlung',
      'T05': 'Abwählen',
      'T06': 'Wählen Sie Alle',
      'T07': 'Main',
      'T08': 'Favoriten',
      'T09': 'Archiv',
      'T10': 'Wird geladen...',
      'T11': 'Zu Favoriten wechseln',
      'T12': 'Zum Archiv verschieben',
      'T13': 'Private Karten können nur von ihrem Besitzer geteilt werden',
      'T14': 'Ok',
      'T15': 'Diese Sammlung ist leer',
      'T16': 'Die Suche ergab keine Ergebnisse',
      'T17': 'Gehe zum Main',
    },
    'japanese': {
      'T00': '選択したカードを本当に削除しますか？ ',
      'T01': 'キャンセル',
      'T02': '削除',
      'T03': '探す...',
      'T04': 'コレクション',
      'T05': '選択を解除',
      'T06': 'すべて選択',
      'T07': 'メイン',
      'T08': 'お気に入り',
      'T09': 'アーカイブ',
      'T10': '読み込み中...',
      'T11': 'お気に入りに移動',
      'T12': 'アーカイブに移動',
      'T13': 'プライベートカードは所有者のみが共有できます',
      'T14': 'Ok',
      'T15': 'このコレクションは空です',
      'T16': '検索結果は得られませんでした',
      'T17': 'メインに移動',
    },
    'italian': {
      'T00': 'Vuoi davvero eliminare le carte selezionate? ',
      'T01': 'Annulla',
      'T02': 'Elimina',
      'T03': 'Ricerca...',
      'T04': 'Collezione',
      'T05': 'Deseleziona',
      'T06': 'Seleziona tutto',
      'T07': 'Principale',
      'T08': 'Preferiti',
      'T09': 'Archivio',
      'T10': 'Caricamento in corso...',
      'T11': 'Sposta in Preferiti',
      'T12': 'Sposta in Archivio',
      'T13': 'La carta privata può essere condivisa solo dal suo proprietario',
      'T14': 'Ok',
      'T15': 'Questa raccolta è vuota',
      'T16': 'La ricerca non ha dato risultati',
      'T17': 'Sposta in Main',
    },
    'french': {
      'T00': 'Voulez-vous vraiment supprimer les cartes sélectionnées? ',
      'T01': 'Annuler',
      'T02': 'Supprimer',
      'T03': 'Chercher...',
      'T04': 'Collection',
      'T05': 'Désélectionner',
      'T06': 'Tout sélectionner',
      'T07': 'Principal',
      'T08': 'Favoris',
      'T09': 'Archiver',
      'T10': 'Chargement...',
      'T11': 'Déplacer vers les favoris',
      'T12': 'Déplacer vers l\'archive',
      'T13': 'La carte privée ne peut être partagée que par son propriétaire',
      'T14': 'Ok',
      'T15': 'Cette collection est vide',
      'T16': 'La recherche n\'a donné aucun résultat',
      'T17': 'Déplacer vers Main',
    },
    'spanish': {
      'T00': '¿Realmente desea eliminar las tarjetas seleccionadas? ',
      'T01': 'Cancelar',
      'T02': 'Eliminar',
      'T03': 'Buscar...',
      'T04': 'Colección',
      'T05': 'Deseleccionar',
      'T06': 'Seleccionar todo',
      'T07': 'Principal',
      'T08': 'Favoritos',
      'T09': 'Archivo',
      'T10': 'Cargando...',
      'T11': 'Mover a Favoritos',
      'T12': 'Mover a Archivo',
      'T13': 'La tarjeta privada solo puede ser compartida por su propietario',
      'T14': 'Ok',
      'T15': 'Esta colección está vacía',
      'T16': 'La búsqueda no dio resultados',
      'T17': 'Mover a Principal',
    },
    'korean': {
      'T00': '선택한 카드를 정말로 삭제 하시겠습니까? ',
      'T01': '취소',
      'T02': '지우다',
      'T03': '검색...',
      'T04': '수집',
      'T05': '선택 취소',
      'T06': '모두 선택',
      'T07': '본관',
      'T08': '즐겨 찾기',
      'T09': '아카이브',
      'T10': '로드 중 ...',
      'T11': '즐겨 찾기로 이동',
      'T12': '아카이브로 이동',
      'T13': '개인 카드는 소유자 만 공유 할 수 있습니다',
      'T14': 'Ok',
      'T15': '이 컬렉션은 비어 있습니다',
      'T16': '검색 결과가 없습니다',
      'T17': '메인으로 이동',
    },
  };

}