class TextSettingsPage {

  final Map<String, Map<String, String>> strings = {
    'english': {
      'T00': 'Pink',
      'T01': 'Red',
      'T02': 'Deep Orange',
      'T03': 'Orange',
      'T04': 'Amber',
      'T05': 'Yellow',
      'T06': 'Lime',
      'T07': 'Light Green',
      'T08': 'Green',
      'T09': 'Teal',
      'T10': 'Cyan',
      'T11': 'Light Blue',
      'T12': 'Blue',
      'T13': 'Indigo',
      'T14': 'Purple',
      'T15': 'Deep Purple',
      'T16': 'Grey',
      'T17': 'Settings',
      'T18': 'Language: ',
      'T19': 'Set to default',
      'T20': 'Color: ',
      'T21': 'Shade: ',
      'T22': 'Apply',
      'T23': 'Sign out',
      'T24': 'About you',
      'T25': 'Cancel',
      'T26': 'Done',
      'T27': 'Verify',
      'T28': 'Verified',
      'T29': 'Verify email',
      'T30': 'A link to verify your email address has been sent',
      'T31': 'Change',
      'T32': 'Authentication',
      'T33': 'Enter password',
      'T34': 'Continue',
      'T35': 'Change email',
      'T36': 'Please enter a valid email address',
      'T37': 'New Email',
      'T38': 'A confirmation link has been sent to your new email address. To complete the change, please follow the link and re-login to the app',
      'T39': 'Could not change, please check internet connection or try again later',
      'T40': 'Email change',
      'T41': 'Ok',
      'T42': 'Error',
      'T43': 'An error occurred in the process. Check if the password you entered is correct or check your internet connection. If you forgot your password, try resetting it',
      'T44': 'Retry',
      'T45': 'Password',
      'T46': 'Reset',
      'T47': 'Password reset',
      'T48': 'To reset your password, follow the link sent to your email address',
      'T49': 'Send a reset link to your email address? ',
      'T50': 'Send',
      'T51': 'Current password',
      'T52': 'Change password',
      'T53': 'Password must contain at least 8 characters',
      'T54': 'Enter a new password',
      'T55': 'New Password',
      'T56': 'The passwords do not match',
      'T57': 'Repeat Password',
      'T58': 'Changed successfully, use your new password the next time you login',
      'T59': 'Password change',
      'T60': 'About App',
      'T61': 'version: ',
      'T62': 'build: ',
      'T63': 'Privacy policy',
      'T64': 'Licenses',
      'T65': 'Close',
      'T66': 'Confirm',
    },
    'russian': {
      'T00': 'Розовый',
      'T01': 'Красный',
      'T02': 'Темно-оранжевый',
      'T03': 'Оранжевый',
      'T04': 'Янтарный',
      'T05': 'Желтый',
      'T06': 'Лайм',
      'T07': 'Светло-зеленый',
      'T08': 'Зеленый',
      'T09': 'Бирюзовый',
      'T10': 'Голубой',
      'T11': 'Светло-синий',
      'T12': 'Синий',
      'T13': 'Индиго',
      'T14': 'Фиолетовый',
      'T15': 'Темно-фиолетовый',
      'T16': 'Серый',
      'T17': 'Настройки',
      'T18': 'Язык: ',
      'T19': 'По умолчанию',
      'T20': 'Цвет: ',
      'T21': 'Оттенок: ',
      'T22': 'Применить',
      'T23': 'Выйти',
      'T24': 'О вас',
      'T25': 'Отмена',
      'T26': 'Готово',
      'T27': 'Подтвердить',
      'T28': 'Подтверждено',
      'T29': 'Подтвердить электронную почту',
      'T30': 'Ссылка для подтверждения вашего электронного адреса отправлена',
      'T31': ' Изменить',
      'T32': 'Аутентификация',
      'T33': 'Введите пароль',
      'T34': 'Продолжить',
      'T35': 'Изменить адрес электронной почты',
      'T36': 'Пожалуйста, введите действительный адрес электронной почты',
      'T37': 'Новая эл. почта',
      'T38': 'Ссылка для подтверждения была отправлена на ваш новый адрес электронной почты. Чтобы завершить изменение, перейдите по ссылке и повторно войдите в приложение.',
      'T39': 'Не удалось изменить, проверьте подключение к Интернету или повторите попытку позже',
      'T40': 'Изменение электронной почты',
      'T41': 'Ok',
      'T42': 'Ошибка',
      'T43': 'Произошла ошибка в процессе. Проверьте правильность введенного пароля или проверьте подключение к Интернету. Если вы забыли пароль, попробуйте его сбросить',
      'T44': 'Повтор',
      'T45': 'Пароль',
      'T46': 'Сброс',
      'T47': 'Сброс пароля',
      'T48': 'Чтобы сбросить пароль, перейдите по ссылке, отправленной на ваш адрес электронной почты',
      'T49': 'Отправить ссылку для сброса на ваш адрес электронной почты?',
      'T50': 'Отправить',
      'T51': 'Текущий пароль',
      'T52': 'Изменить пароль',
      'T53': 'Пароль должен содержать не менее 8 символов',
      'T54': 'Введите новый пароль',
      'T55': 'Новый пароль',
      'T56': 'Пароли не совпадают',
      'T57': 'Повторите пароль',
      'T58': 'Изменен успешно, используйте новый пароль при следующем входе в приложение',
      'T59': 'Изменение пароля',
      'T60': 'О приложении',
      'T61': 'версия: ',
      'T62': 'сборка: ',
      'T63': 'Политика конфиденциальности',
      'T64': 'Лицензии',
      'T65': 'Закрыть',
      'T66': 'Подтвердить',
    },
    'german': {
      'T00': 'Rosa',
      'T01': 'Rot',
      'T02': 'Tiefes Orange',
      'T03': 'Orange',
      'T04': 'Bernstein',
      'T05': 'Gelb',
      'T06': 'Limette',
      'T07': 'Hellgrün',
      'T08': 'Grün',
      'T09': 'Blaugrün',
      'T10': 'Cyan',
      'T11': 'Hellblau',
      'T12': 'Blau',
      'T13': 'Indigo',
      'T14': 'Lila',
      'T15': 'Dunkelviolett',
      'T16': 'Grau',
      'T17': 'Einstellungen',
      'T18': 'Sprache: ',
      'T19': 'Auf Standard setzen',
      'T20': 'Farbe: ',
      'T21': 'Schatten: ',
      'T22': 'Anwenden',
      'T23': 'Ausloggen',
      'T24': 'Über dich',
      'T25': 'Stornieren',
      'T26': 'Erledigt',
      'T27': 'Überprüfen',
      'T28': 'Verifiziert',
      'T29': 'E-Mail bestätigen',
      'T30': 'Ein Link zur Überprüfung Ihrer E-Mail-Adresse wurde gesendet',
      'T31': 'Veränderung',
      'T32': 'Authentifizierung',
      'T33': 'Passwort eingeben',
      'T34': 'Fortsetzen',
      'T35': 'Ändern Sie die E-Mail',
      'T36': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
      'T37': 'Neue e-mail',
      'T38': 'Ein Bestätigungslink wurde an Ihre neue E-Mail-Adresse gesendet. Um die Änderung abzuschließen, folgen Sie bitte dem Link und melden Sie sich erneut bei der App an',
      'T39': 'Konnte nicht geändert werden, überprüfen Sie die Internetverbindung oder versuchen Sie es später erneut',
      'T40': 'E-Mail-Änderung',
      'T41': 'Ok',
      'T42': 'Error',
      'T43': 'Dabei ist ein Fehler aufgetreten. Überprüfen Sie, ob das eingegebene Passwort korrekt ist, oder überprüfen Sie Ihre Internetverbindung. Wenn Sie Ihr Passwort vergessen haben, setzen Sie es zurück',
      'T44': 'Wiederholen',
      'T45': 'Passwort',
      'T46': 'Zurücksetzen',
      'T47': 'Passwort zurücksetzen',
      'T48': 'Um Ihr Passwort zurückzusetzen, folgen Sie dem Link, der an Ihre E-Mail-Adresse gesendet wurde',
      'T49': 'Einen Reset-Link an Ihre E-Mail-Adresse senden? ',
      'T50': 'Senden',
      'T51': 'Derzeitiges Passwort',
      'T52': 'Passwort ändern',
      'T53': 'Das Passwort muss mindestens 8 Zeichen enthalten',
      'T54': 'Geben Sie ein neues Kennwort ein',
      'T55': 'Neues Kennwort',
      'T56': 'Die Passwörter stimmen nicht überein',
      'T57': 'Passwort wiederholen',
      'T58': 'Bei erfolgreicher Änderung verwenden Sie Ihr neues Passwort, wenn Sie sich das nächste Mal anmelden',
      'T59': 'Passwortänderung',
      'T60': 'Über App',
      'T61': 'ausführung: ',
      'T62': 'bauen: ',
      'T63': 'Datenschutz-Bestimmungen',
      'T64': 'Lizenzen',
      'T65': 'Schließen',
      'T66': 'Bestätigen',
    },
    'japanese': {
      'T00': '淡紅色',
      'T01': '赤',
      'T02': 'ディープオレンジ',
      'T03': 'オレンジ',
      'T04': 'アンバー',
      'T05': '黄',
      'T06': 'ライム',
      'T07': 'ライトグリーン',
      'T08': '緑',
      'T09': 'ティール',
      'T10': 'シアン',
      'T11': 'ライトブルー',
      'T12': '青',
      'T13': 'インジゴ',
      'T14': '紫の',
      'T15': 'ディープ・パープル',
      'T16': 'グレー',
      'T17': '設定',
      'T18': '言語：',
      'T19': 'デフォルトに設定',
      'T20': '色：',
      'T21': 'シェード：',
      'T22': '適用する',
      'T23': 'サインアウト',
      'T24': 'あなたについて',
      'T25': 'キャンセル',
      'T26': '完了',
      'T27': '確認',
      'T28': '確認済み',
      'T29': 'Eメールを確認します',
      'T30': 'メールアドレスを確認するためのリンクが送信されました',
      'T31': '変化する',
      'T32': '認証',
      'T33': 'パスワードを入力する',
      'T34': '継続する',
      'T35': 'メールアドレスを変更',
      'T36': '有効なメールアドレスを入力してください',
      'T37': '新しいメール',
      'T38': '新しいメールアドレスに確認リンクが送信されました。 変更を完了するには、リンクをたどってアプリに再ログインしてください',
      'T39': '変更できませんでした。インターネット接続を確認するか、後でもう一度お試しください',
      'T40': 'メールの変更',
      'T41': 'Ok',
      'T42': 'エラー',
      'T43': 'プロセスでエラーが発生しました。 入力したパスワードが正しいかどうか、またはインターネット接続を確認してください。 パスワードを忘れた場合は、リセットしてみてください',
      'T44': 'リトライ',
      'T45': 'パスワード',
      'T46': 'リセット',
      'T47': 'パスワードのリセット',
      'T48': 'パスワードをリセットするには、メールアドレスに送信されたリンクをたどってください',
      'T49': 'あなたのメールアドレスにリセットリンクを送信しますか？ ',
      'T50': '送信',
      'T51': '現在のパスワード',
      'T52': 'パスワードを変更する',
      'T53': 'パスワードには8文字以上が含まれている必要があります',
      'T54': '新しいパスワードを入力',
      'T55': '新しいパスワード',
      'T56': 'パスワードが一致しません',
      'T57': 'パスワードを再度入力してください',
      'T58': '正常に変更されました。次回ログインするときに新しいパスワードを使用してください',
      'T59': 'パスワードの変更',
      'T60': 'アプリについて',
      'T61': 'バージョン： ',
      'T62': 'ビルド： ',
      'T63': '個人情報保護方針',
      'T64': 'ライセンス',
      'T65': '閉じる',
      'T66': '確認',
    },
    'italian': {
      'T00': 'Rosa',
      'T01': 'Rosso',
      'T02': 'Arancio intenso',
      'T03': 'Arancio',
      'T04': 'Ambra',
      'T05': 'Giallo',
      'T06': 'Lime',
      'T07': 'Verde chiaro',
      'T08': 'Verde',
      'T09': 'Teal',
      'T10': 'Ciano',
      'T11': 'Azzurro',
      'T12': 'Blu',
      'T13': 'Indaco',
      'T14': 'Viola',
      'T15': 'Viola profondo',
      'T16': 'Grigio',
      'T17': 'Impostazioni',
      'T18': 'Linguaggio: ',
      'T19': 'Imposta come predefinito',
      'T20': 'Colore: ',
      'T21': 'Ombra: ',
      'T22': 'Applicare',
      'T23': 'Disconnessione',
      'T24': 'A proposito di te',
      'T25': 'Annulla',
      'T26': 'Fatto',
      'T27': 'Verificare',
      'T28': 'Verificato',
      'T29': 'Verifica email',
      'T30': 'È stato inviato un collegamento per verificare il tuo indirizzo email',
      'T31': 'Modificare',
      'T32': 'Autenticazione',
      'T33': 'Inserire la password',
      'T34': 'Continua',
      'T35': 'Cambia email',
      'T36': 'Si prega di inserire un indirizzo email valido',
      'T37': 'Nuova email',
      'T38': 'Un link di conferma è stato inviato al tuo nuovo indirizzo email. Per completare la modifica, segui il link e accedi nuovamente all\'app',
      'T39': 'Impossibile modificare, controlla la connessione a Internet o riprova più tardi',
      'T40': 'Modifica dell\'email',
      'T41': 'Ok',
      'T42': 'Errore',
      'T43': 'Si è verificato un errore nel processo. Controlla se la password che hai inserito è corretta o controlla la tua connessione Internet. Se hai dimenticato la password, prova a reimpostarla',
      'T44': 'Riprova',
      'T45': 'Password',
      'T46': 'Ripristina',
      'T47': 'Reimpostazione della password',
      'T48': 'Per reimpostare la password, segui il link inviato al tuo indirizzo email',
      'T49': 'Inviare un collegamento di ripristino al tuo indirizzo email? ',
      'T50': 'Spedire',
      'T51': 'Password attuale',
      'T52': 'Cambia la password',
      'T53': 'La password deve contenere almeno 8 caratteri',
      'T54': 'Inserisci una nuova password',
      'T55': 'Nuova password',
      'T56': 'Le password non corrispondono',
      'T57': 'Ripeti la password',
      'T58': 'Modificata con successo, usa la tua nuova password al prossimo accesso',
      'T59': 'Cambio di password',
      'T60': 'Informazioni sull\'app',
      'T61': 'versione: ',
      'T62': 'costruire: ',
      'T63': 'Politica sulla riservatezza',
      'T64': 'Licenze',
      'T65': 'Chiudi',
      'T66': 'Confermare',
    },
    'french': {
      'T00': 'Rose',
      'T01': 'Rouge',
      'T02': 'Orange foncé',
      'T03': 'Orange',
      'T04': 'Ambre',
      'T05': 'Jaune',
      'T06': 'Citron vert',
      'T07': 'Vert clair',
      'T08': 'Vert',
      'T09': 'Sarcelle',
      'T10': 'Cyan',
      'T11': 'Bleu clair',
      'T12': 'Bleu',
      'T13': 'Indigo',
      'T14': 'Violet',
      'T15': 'Violet foncé',
      'T16': 'Gris',
      'T17': 'Réglages',
      'T18': 'Langue: ',
      'T19': 'Définir par défaut',
      'T20': 'Couleur: ',
      'T21': 'Ombre: ',
      'T22': 'Appliquer',
      'T23': 'Déconnexion',
      'T24': 'Au propos de vous',
      'T25': 'Annuler',
      'T26': 'Terminé',
      'T27': 'Vérifier',
      'T28': 'Vérifié',
      'T29': 'Vérifier les courriels',
      'T30': 'Un lien pour vérifier votre adresse e-mail a été envoyé',
      'T31': 'Changement',
      'T32': 'Authentification',
      'T33': 'Entrer le mot de passe',
      'T34': 'Continuer',
      'T35': 'Changer l\'e-mail',
      'T36': 'S\'il vous plaît, mettez une adresse email valide',
      'T37': 'Nouveau e-mail',
      'T38': 'Un lien de confirmation a été envoyé à votre nouvelle adresse e-mail. Pour terminer le changement, veuillez suivre le lien et vous reconnecter à l\'application',
      'T39': 'Impossible de changer, veuillez vérifier la connexion Internet ou réessayer plus tard',
      'T40': 'Changement e-mail',
      'T41': 'Ok',
      'T42': 'Erreur',
      'T43': 'Une erreur s\'est produite dans le processus. Vérifiez si le mot de passe que vous avez entré est correct ou vérifiez votre connexion Internet. Si vous avez oublié votre mot de passe, essayez de le réinitialiser',
      'T44': 'Réessayez',
      'T45': 'Mot de passe',
      'T46': 'Réinitialiser',
      'T47': 'Réinitialisation du mot de passe',
      'T48': 'Pour réinitialiser votre mot de passe, suivez le lien envoyé à votre adresse e-mail',
      'T49': 'Envoyer un lien de réinitialisation à votre adresse e-mail? ',
      'T50': 'Envoyer',
      'T51': 'Mot de passe actuel',
      'T52': 'Changer le mot de passe',
      'T53': 'Le mot de passe doit contenir au moins 8 caractères',
      'T54': 'Entrer un nouveau mot de passe',
      'T55': 'Nouveau mot de passe',
      'T56': 'Le mot de passe ne correspond pas',
      'T57': 'Répéter le mot de passe',
      'T58': 'Changé avec succès, utilisez votre nouveau mot de passe la prochaine fois que vous vous connectez',
      'T59': 'Changement de mot de passe',
      'T60': 'À propos de l\'application',
      'T61': 'version: ',
      'T62': 'construire: ',
      'T63': 'Politique de confidentialité',
      'T64': 'Licences',
      'T65': 'Ferme',
      'T66': 'Confirmer',
    },
    'spanish': {
      'T00': 'Rosado',
      'T01': 'Rojo',
      'T02': 'Naranja intenso',
      'T03': 'Naranja',
      'T04': 'Ámbar',
      'T05': 'Amarillo',
      'T06': 'Lima',
      'T07': 'Verde claro',
      'T08': 'Verde',
      'T09': 'Verde azulado',
      'T10': 'Cian',
      'T11': 'Azul claro',
      'T12': 'Azul',
      'T13': 'Índigo',
      'T14': 'Morado',
      'T15': 'Morado oscuro',
      'T16': 'Gris',
      'T17': 'Configuraciones',
      'T18': 'Idioma: ',
      'T19': 'Establecer como predeterminado',
      'T20': 'Color: ',
      'T21': 'Sombra: ',
      'T22': 'Aplicar',
      'T23': 'Desconectar',
      'T24': 'Acerca de ti',
      'T25': 'Cancelar',
      'T26': 'Hecho',
      'T27': 'Verificar',
      'T28': 'Verificado',
      'T29': 'Verificar e-mail',
      'T30': 'Se ha enviado un enlace para verificar su dirección de correo electrónico',
      'T31': 'Cambio',
      'T32': 'Autenticación',
      'T33': 'Introducir la contraseña',
      'T34': 'Seguir',
      'T35': 'Cambiar e-mail',
      'T36': 'Por favor, introduce una dirección de correo electrónico válida',
      'T37': 'Nuevo correo electrónico',
      'T38': 'Se ha enviado un enlace de confirmación a su nueva dirección de correo electrónico. Para completar el cambio, siga el enlace y vuelva a iniciar sesión en la aplicación',
      'T39': 'No se pudo cambiar, verifique la conexión a Internet o intente nuevamente más tarde',
      'T40': 'Cambio de correo electrónico',
      'T41': 'Ok',
      'T42': 'Error',
      'T43': 'Ocurrió un error en el proceso. Verifique si la contraseña que ingresó es correcta o verifique su conexión a Internet. Si olvidó su contraseña, intente restablecerla',
      'T44': 'Rever',
      'T45': 'Contraseña',
      'T46': 'Reiniciar',
      'T47': 'Restablecimiento de contraseña',
      'T48': 'Para restablecer su contraseña, siga el enlace enviado a su dirección de correo electrónico',
      'T49': '¿Enviar un enlace de restablecimiento a su dirección de correo electrónico? ',
      'T50': 'Enviar',
      'T51': 'Contraseña actual',
      'T52': 'Cambia la contraseña',
      'T53': 'La contraseña debe contener al menos 8 caracteres',
      'T54': 'Introduzca una nueva contraseña',
      'T55': 'Nueva contraseña',
      'T56': 'las contraseñas no coinciden',
      'T57': 'Repite la contraseña',
      'T58': 'Cambiada correctamente, use su nueva contraseña la próxima vez que inicie sesión',
      'T59': 'Cambio de contraseña',
      'T60': 'Acerca de la aplicación',
      'T61': 'versión: ',
      'T62': 'construir: ',
      'T63': 'Política de privacidad',
      'T64': 'Licencias',
      'T65': 'Cerrar',
      'T66': 'Confirmar',
    },
    'korean': {
      'T00': '분홍',
      'T01': '빨간',
      'T02': '딥 오렌지',
      'T03': '주황색',
      'T04': '호박색',
      'T05': '노랑',
      'T06': '라임',
      'T07': '연한 초록색',
      'T08': '초록',
      'T09': '물오리',
      'T10': '청록색',
      'T11': '하늘색',
      'T12': '푸른',
      'T13': '남빛',
      'T14': '보라색',
      'T15': '짙은 보라',
      'T16': '회색',
      'T17': '설정',
      'T18': '언어: ',
      'T19': '기본값으로 설정',
      'T20': '색깔: ',
      'T21': '그늘: ',
      'T22': '대다',
      'T23': '로그 아웃',
      'T24': '당신에 대해',
      'T25': '취소',
      'T26': '끝난',
      'T27': '확인',
      'T28': '확인 됨',
      'T29': '이메일 확인',
      'T30': '이메일 주소를 확인하는 링크가 전송되었습니다',
      'T31': '변화',
      'T32': '입증',
      'T33': '암호를 입력',
      'T34': '계속하다',
      'T35': '이메일을 바꾸다',
      'T36': '유효한 이메일 주소를 입력하세요',
      'T37': '새 이메일',
      'T38': '새 이메일 주소로 확인 링크가 전송되었습니다. 변경을 완료하려면 링크를 따라 앱에 다시 로그인하세요',
      'T39': '변경할 수 없습니다. 인터넷 연결을 확인하거나 나중에 다시 시도하십시오',
      'T40': '이메일 변경',
      'T41': 'Ok',
      'T42': '오류',
      'T43': '프로세스에서 오류가 발생했습니다. 입력 한 비밀번호가 정확한지 확인하거나 인터넷 연결을 확인하세요. 비밀번호를 잊은 경우 재설정 해보십시오',
      'T44': '다시 해 보다',
      'T45': '암호',
      'T46': '초기화',
      'T47': '비밀번호 초기화',
      'T48': '비밀번호를 재설정하려면 이메일 주소로 전송 된 링크를 따르세요',
      'T49': '이메일 주소로 재설정 링크를 보내시겠습니까? ',
      'T50': '보내다',
      'T51': '현재 비밀번호',
      'T52': '비밀번호 변경',
      'T53': '비밀번호는 8 자 이상이어야합니다',
      'T54': '새 비밀번호를 입력하세요',
      'T55': '새 비밀번호',
      'T56': '암호가 일치하지 않습니다',
      'T57': '비밀번호 반복',
      'T58': '성공적으로 변경되었습니다. 다음에 로그인 할 때 새 암호를 사용하십시오',
      'T59': '비밀번호 변경',
      'T60': '앱 정보',
      'T61': '버전: ',
      'T62': '짓다: ',
      'T63': '개인 정보 정책',
      'T64': '라이선스',
      'T65': '닫기',
      'T66': '확인',
    },
  };

}