class TextScanModule {

  final Map<String, Map<String, String>> strings = {
    'english': {
      'T00': 'Add',
      'T01': 'The device does not support this data transfer method',
      'T02': 'NFC module is active',
      'T03': 'Enable NFC module',
      'T04': 'NFC support will be added soon. Until then, please use the QR-code or the link',
      'T05': 'NFC module is unavailable',
      'T06': 'Back',
      'T07': 'Ok',
    },
    'russian': {
      'T00': 'Добавить',
      'T01': 'Устройство не поддерживает данный метод передачи данных',
      'T02': 'Модуль NFC активен',
      'T03': 'Включить модуль NFC',
      'T04': 'Поддержка NFC будет добавлена скоро. А пока, пожалуйста, используйте QR-код или ссылку',
      'T05': 'Модуль NFC недоступен',
      'T06': 'Назад',
      'T07': 'Ok',
    },
    'german': {
      'T00': 'Hinzufügen',
      'T01': 'Das Gerät unterstützt diese Datenübertragungsmethode nicht',
      'T02': 'NFC-Modul ist aktiv',
      'T03': 'Aktivieren Sie das NFC-Modul',
      'T04': 'NFC-Unterstützung wird in Kürze hinzugefügt. Bis dahin benutzen Sie bitte den QR-Code oder den Link',
      'T05': 'NFC-Modul ist nicht verfügbar',
      'T06': 'Zurück',
      'T07': 'Ok',
    },
    'japanese': {
      'T00': '追加',
      'T01': 'デバイスはこのデータ転送方法をサポートしていません',
      'T02': 'NFCモジュールがアクティブです',
      'T03': 'NFCモジュールを有効にする',
      'T04': 'NFCサポートはまもなく追加されます。 それまでは、QRコードまたはリンクをご利用ください',
      'T05': 'NFCモジュールは利用できません',
      'T06': '裏面',
      'T07': 'Ok',
    },
    'italian': {
      'T00': 'Inserisci',
      'T01': 'Il dispositivo non supporta questo metodo di trasferimento dati',
      'T02': 'Il modulo NFC è attivo',
      'T03': 'Abilita modulo NFC',
      'T04': 'Presto verrà aggiunto il supporto NFC. Fino ad allora, utilizza il codice QR o il link',
      'T05': 'Il modulo NFC non è disponibile',
      'T06': 'Indietro',
      'T07': 'Ok',
    },
    'french': {
      'T00': 'Ajouter',
      'T01': 'L\'appareil ne prend pas en charge cette méthode de transfert de données',
      'T02': 'Le module NFC est actif',
      'T03': 'Activer le module NFC',
      'T04': 'Le support NFC sera bientôt ajouté. D\'ici là, veuillez utiliser le code QR ou le lien',
      'T05': 'Le module NFC n\'est pas disponible',
      'T06': 'Retour',
      'T07': 'Ok',
    },
    'spanish': {
      'T00': 'Añadir',
      'T01': 'El dispositivo no admite este método de transferencia de datos',
      'T02': 'El módulo NFC está activo',
      'T03': 'Habilitar el módulo NFC',
      'T04': 'La compatibilidad con NFC se agregará pronto. Hasta entonces, utilice el código QR o el enlace',
      'T05': 'El módulo NFC no está disponible',
      'T06': 'Atrás',
      'T07': 'Ok',
    },
    'korean': {
      'T00': '더하다',
      'T01': '장치가이 데이터 전송 방법을 지원하지 않습니다',
      'T02': 'NFC 모듈이 활성화 됨',
      'T03': 'NFC 모듈 활성화',
      'T04': 'NFC 지원이 곧 추가 될 예정입니다. 그때까지는 QR 코드 또는 링크를 사용하십시오',
      'T05': 'NFC 모듈을 사용할 수 없습니다',
      'T06': '뒤',
      'T07': 'Ok',
    },
  };

}