class TextAuthPage {

  final Map<String, Map<String, String?>> strings = {
    'english': {
      'T00': 'Please enter a valid email address',
      'T01': 'This field is required',
      'T02': 'Password must contain at least 8 characters',
      'T03': 'Welcome!',
      'T04': 'Don\'t have an account yet?  ',
      'T05': 'Sign Up',
      'T06': 'Email*',
      'T07': 'Password*',
      'T08': 'Forgot password?',
      'T09': 'Log In',
      'T10': 'Please enter your password',
      'T11': 'Already have an account?  ',
      'T12': 'The passwords do not match',
      'T13': 'Confirm password*',
      'T14': 'Account Name*',
      'T15': 'language',
      'T16': 'Please enter your accounts name and email address to receive a reset password link',
      'T17': 'Send',
      'T18': 'Please use only English letters and numbers',
      'T19': 'Maximum length of the name is 32 characters',
      'T20': 'Name is free to use',
      'T21': 'Name is already taken',
      'T22': 'Checking name...',
      'T23': 'Error occurred while signing up',
      'T24': 'Please fill in all required fields with correct information',
      'T25': 'Unique Account Name is required',
      'T26': 'Please wait until Account Name will be checked',
      'T27': 'Could not log in with provided credentials',
      'T28': 'Please check your internet connection and try again',
      'T29': 'Terms of service and Privacy policy',
      'T30': 'Please read and accept',
      'T31': 'Accept',
      'T32': 'Decline',
      'T33': 'Ok',
      'T34': 'Error',

      'null': null,
    },
    'russian': {
      'T00': 'Введите действующий адрес электронной почты',
      'T01': 'Поле обязательно для заполнения',
      'T02': 'Пароль должен содержать не менее 8 знаков',
      'T03': 'Добро пожаловать!',
      'T04': 'У вас еще нет аккаунта?  ',
      'T05': 'Зарегистрироваться',
      'T06': 'Электронная почта*',
      'T07': 'Пароль*',
      'T08': 'Забыли пароль?',
      'T09': 'Войти',
      'T10': 'Пожалуйста, введите ваш пароль',
      'T11': 'Уже зарегистрированы?  ',
      'T12': 'Пароли не совпадают',
      'T13': 'Подтверждение пароля*',
      'T14': 'Имя аккаунта*',
      'T15': 'язык',
      'T16': 'Пожалуйста, введите ваши имя аккаунта и адрес электронной почты, чтобы получить письмо со ссылкой для сброса пароля',
      'T17': 'Отправить',
      'T18': 'Используйте только английские буквы и цифры',
      'T19': 'Максимальная длина имени - 32 символа',
      'T20': 'Имя свободно',
      'T21': 'Имя уже занято',
      'T22': 'Проверка имени...',
      'T23': 'Ошибка при регистрации',
      'T24': 'Пожалуйста, заполните все поля корректной информацией',
      'T25': 'Необходимо уникальное имя аккаунта',
      'T26': 'Подождите, пока имя учетной записи не будет проверено',
      'T27': 'Не удалось войти с предоставленными учетными данными',
      'T28': 'Пожалуйста, проверьте ваше интернет-соединение и попробуйте еще раз',
      'T29': 'Примите Условия использования и Политику конфиденциальности',
      'T30': 'Пожалуйста, прочтите и примите',
      'T31': 'Принять',
      'T32': 'Отклонить',
      'T33': 'Ok',
      'T34': 'Ошибка',

      'null': null,
    },
    'german': {
      'T00': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
      'T01': 'Dieses Feld wird benötigt',
      'T02': 'Das Passwort muss mindestens 8 Zeichen enthalten',
      'T03': 'Herzlich willkommen!',
      'T04': 'Sie haben noch keinen Account?  ',
      'T05': 'Registrieren',
      'T06': 'Email*',
      'T07': 'Passwort*',
      'T08': 'Passwort vergessen?',
      'T09': 'Anmelden',
      'T10': 'Bitte geben Sie Ihr Passwort ein',
      'T11': 'Sie haben bereits ein Konto?  ',
      'T12': 'Die Passwörter stimmen nicht überein',
      'T13': 'Bestätige das Passwort*',
      'T14': 'Kontobezeichnung*',
      'T15': 'sprache',
      'T16': 'Bitte geben Sie Ihren Kontonamen und Ihre E-Mail-Adresse ein, um einen Link zum Zurücksetzen des Passworts zu erhalten',
      'T17': 'Senden',
      'T18': 'Bitte verwenden Sie nur englische Buchstaben und Zahlen',
      'T19': 'Die maximale Länge des Namens beträgt 32 Zeichen',
      'T20': 'Der Name kann kostenlos verwendet werden',
      'T21': 'Name ist bereits vergeben',
      'T22': 'Name überprüfen...',
      'T23': 'Bei der Anmeldung ist ein Fehler aufgetreten',
      'T24': 'Bitte füllen Sie alle erforderlichen Felder mit den richtigen Informationen aus',
      'T25': 'Ein eindeutiger Kontoname ist erforderlich',
      'T26': 'Bitte warten Sie, bis der Kontoname überprüft wird',
      'T27': 'Konnte sich nicht mit den angegebenen Anmeldeinformationen anmelden',
      'T28': 'Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut',
      'T29': 'Stimmen Sie den Nutzungsbedingungen und den Datenschutzbestimmungen zu',
      'T30': 'Bitte lesen und akzeptieren',
      'T31': 'Akzeptieren',
      'T32': 'Ablehnen',
      'T33': 'Ok',
      'T34': 'Error',

      'null': null,
    },
    'japanese': {
      'T00': '有効なメールアドレスを入力してください',
      'T01': 'この項目は必須です',
      'T02': 'パスワードには8文字以上が必要です',
      'T03': 'ようこそ！',
      'T04': 'アカウントなし？  ',
      'T05': 'サインアップ',
      'T06': 'Eメール*',
      'T07': 'パスワード*',
      'T08': 'パスワードをお忘れですか？',
      'T09': 'ログインする',
      'T10': 'パスワードを入力してください',
      'T11': 'アカウントを持っています？  ',
      'T12': 'パスワードが一致しません',
      'T13': 'パスワードを認証する*',
      'T14': 'アカウント名*',
      'T15': '言語',
      'T16': 'パスワードのリセットリンクを受け取るには、アカウント名とメールアドレスを入力してください',
      'T17': '送信',
      'T18': '英語の文字と数字のみを使用してください',
      'T19': '名前の最大長は32文字です',
      'T20': '名前は自由に使用できます',
      'T21': '名前はすでに取られています',
      'T22': '名前を確認しています...',
      'T23': 'サインアップ中にエラーが発生しました',
      'T24': 'すべての必須フィールドに正しい情報を入力してください',
      'T25': '一意のアカウント名が必要です',
      'T26': 'アカウント名が確認されるまでお待ちください',
      'T27': '提供された資格情報でログインできませんでした',
      'T28': 'インターネット接続を確認して、もう一度お試しください',
      'T29': '利用規約とプライバシーポリシーに同意する',
      'T30': '読んで受け入れてください',
      'T31': '受け入れる',
      'T32': '低下',
      'T33': 'Ok',
      'T34': 'エラー',

      'null': null,
    },
    'italian': {
      'T00': 'Si prega di inserire un indirizzo email valido',
      'T01': 'Questo campo è obbligatorio',
      'T02': 'La password deve contenere almeno 8 caratteri',
      'T03': 'Benvenuto!',
      'T04': 'Non hai ancora un conto?  ',
      'T05': 'Iscriviti',
      'T06': 'E-mail*',
      'T07': 'Parola d\'ordine*',
      'T08': 'Ha dimenticato la password?',
      'T09': 'Accesso',
      'T10': 'Si prega di inserire la password',
      'T11': 'Hai già un account?  ',
      'T12': 'Le password non corrispondono',
      'T13': 'Conferma password*',
      'T14': 'Nome utente*',
      'T15': 'linguaggio',
      'T16': 'Inserisci il nome del tuo account e l\'indirizzo e-mail per ricevere un link per reimpostare la password',
      'T17': 'Spedire',
      'T18': 'Utilizzare solo lettere e numeri inglesi',
      'T19': 'La lunghezza massima del nome è di 32 caratteri',
      'T20': 'Il nome è gratuito',
      'T21': 'Il nome è già stato preso',
      'T22': 'Controllo del nome ...',
      'T23': 'Si è verificato un errore durante la registrazione',
      'T24': 'Si prega di compilare tutti i campi obbligatori con le informazioni corrette',
      'T25': 'È richiesto un nome account univoco',
      'T26': 'Attendi fino a quando il nome dell\'account verrà verificato',
      'T27': 'Impossibile accedere con le credenziali fornite',
      'T28': 'Controlla la tua connessione Internet e riprova',
      'T29': 'Termini di servizio e informativa sulla privacy',
      'T30': 'Si prega di leggere e accettare',
      'T31': 'Accettare',
      'T32': 'Declino',
      'T33': 'Ok',
      'T34': 'Errore',

      'null': null,
    },
    'french': {
      'T00': 'S\'il vous plaît, mettez une adresse email valide',
      'T01': 'Ce champ est requis',
      'T02': 'Le mot de passe doit contenir au moins 8 caractères',
      'T03': 'Bienvenu!',
      'T04': 'Vous n\'avez pas encore de compte?  ',
      'T05': 'S\'inscrire',
      'T06': 'Email*',
      'T07': 'Mot de passe*',
      'T08': 'Mot de passe oublié?',
      'T09': 'S\'identifier',
      'T10': 'Veuillez entrer votre mot de passe',
      'T11': 'Vous avez déjà un compte?  ',
      'T12': 'Le mot de passe ne correspond pas',
      'T13': 'Confirmez le mot de passe*',
      'T14': 'Nom du compte*',
      'T15': 'le langage',
      'T16': 'Veuillez saisir le nom de votre compte et votre adresse e-mail pour recevoir un lien de réinitialisation du mot de passe',
      'T17': 'Envoyer',
      'T18': 'Veuillez n\'utiliser que des lettres et des chiffres anglais',
      'T19': 'La longueur maximale du nom est de 32 caractères',
      'T20': 'Le nom est libre d\'utilisation',
      'T21': 'Le nom est déjà pris',
      'T22': 'Vérification du nom...',
      'T23': 'Une erreur s\'est produite lors de l\'inscription',
      'T24': 'Veuillez remplir tous les champs obligatoires avec des informations correctes',
      'T25': 'Un nom de compte unique est requis',
      'T26': 'Veuillez attendre que le nom du compte soit vérifié',
      'T27': 'Impossible de se connecter avec les informations d\'identification fournies',
      'T28': 'S\'il vous plaît, vérifiez votre connexion à internet et réessayez',
      'T29': 'Conditions d\'utilisation et politique de confidentialité',
      'T30': 'Veuillez lire et accepter',
      'T31': 'J\'accepte',
      'T32': 'Déclin',
      'T33': 'Ok',
      'T34': 'Erreur',

      'null': null,
    },
    'spanish': {
      'T00': 'Por favor, introduce una dirección de correo electrónico válida',
      'T01': 'Este campo es obligatorio',
      'T02': 'La contraseña debe contener al menos 8 caracteres',
      'T03': '¡Bienvenido!',
      'T04': '¿Aún no tienes una cuenta?  ',
      'T05': 'Regístrate',
      'T06': 'Correo electrónico*',
      'T07': 'Contraseña*',
      'T08': '¿Se te olvidó tu contraseña?',
      'T09': 'Iniciar sesión',
      'T10': 'Por favor, introduzca su contraseña',
      'T11': '¿Ya tienes una cuenta?  ',
      'T12': 'las contraseñas no coinciden',
      'T13': 'Confirmar contraseña*',
      'T14': 'Nombre de la cuenta*',
      'T15': 'idioma',
      'T16': 'Ingrese el nombre y la dirección de correo electrónico de su cuenta para recibir un enlace para restablecer la contraseña',
      'T17': 'Enviar',
      'T18': 'Utilice solo letras y números en inglés',
      'T19': 'La longitud máxima del nombre es de 32 caracteres',
      'T20': 'El nombre es de uso gratuito',
      'T21': 'Nombre ya usado',
      'T22': 'Comprobando nombre...',
      'T23': 'Se produjo un error al registrarse',
      'T24': 'Complete todos los campos obligatorios con la información correcta',
      'T25': 'Se requiere un nombre de cuenta único',
      'T26': 'Espere hasta que se verifique el nombre de la cuenta',
      'T27': 'No se pudo iniciar sesión con las credenciales proporcionadas',
      'T28': 'Comprueba tu conexión a Internet y vuelve a intentarlo',
      'T29': 'Termino del servicio y política de privacidad',
      'T30': 'Por favor lea y acepte',
      'T31': 'Aceptar',
      'T32': 'Disminución',
      'T33': 'Ok',
      'T34': 'Error',

      'null': null,
    },
    'korean': {
      'T00': '유효한 이메일 주소를 입력하세요',
      'T01': '이 필드는 필수입니다',
      'T02': '비밀번호는 8 자 이상이어야합니다',
      'T03': '어서 오십시오!',
      'T04': '아직 계정이 없으십니까?  ',
      'T05': '가입하기',
      'T06': '이메일*',
      'T07': '암호*',
      'T08': '비밀번호를 잊으 셨나요?',
      'T09': '로그인',
      'T10': '비밀번호를 입력하세요',
      'T11': '이미 계정이 있습니까?  ',
      'T12': '암호가 일치하지 않습니다',
      'T13': '비밀번호 확인*',
      'T14': '계정 이름*',
      'T15': '언어',
      'T16': '비밀번호 재설정 링크를 받으려면 계정 이름과 이메일 주소를 입력하세요',
      'T17': '보내다',
      'T18': '영문자와 숫자 만 사용하세요',
      'T19': '이름의 최대 길이는 32 자입니다',
      'T20': '이름은 무료로 사용할 수 있습니다',
      'T21': '이미 사용중인 이름입니다',
      'T22': '이름 확인 중 ...',
      'T23': '가입하는 동안 오류가 발생했습니다',
      'T24': '모든 필수 필드에 올바른 정보를 입력하십시오',
      'T25': '고유 계정 이름이 필요합니다',
      'T26': '계정 이름이 확인 될 때까지 기다리십시오',
      'T27': '제공된 자격 증명으로 로그인 할 수 없습니다',
      'T28': '인터넷 연결을 확인하고 다시 시도하십시오',
      'T29': '서비스 약관 및 개인 정보 보호 정책',
      'T30': '읽고 동의하십시오',
      'T31': '동의하기',
      'T32': '쇠퇴',
      'T33': 'Ok',
      'T34': '오류',

      'null': null ,
    },
  };

}