class TextProfilePage {
  final Map<String, Map<String, String>> strings = {
    'english': {
      'T00': 'Profile',
      'T01': 'Blocking',
      'T02': 'Unblocking',
      'T03': 'Do you really want to block access to your card for ',
      'T04': 'Unblock ',
      'T05': 'Cancel',
      'T06': 'Yes',
      'T07': 'User is unblocked and can access your card',
      'T08': 'User is blocked and no longer have access to your card until unblocked',
      'T09': 'Error has occurred. Could not perform operation. Please try again later',
      'T10': 'Ok',
      'T11': 'Blocked',
      'T12': 'Block ',
    },
    'russian': {
      'T00': 'Профиль',
      'T01': 'Блокировка',
      'T02': 'Разблокировка',
      'T03': 'Вы действительно хотите заблокировать доступ к своей карте для ',
      'T04': 'Разблокировать ',
      'T05': 'Отмена',
      'T06': 'Да',
      'T07': 'Пользователь разблокирован и может получить доступ к вашей карте',
      'T08': 'Пользователь заблокирован и больше не имеет доступа к вашей карте, пока не будет разблокирован',
      'T09': 'Произошла ошибка. Не удалось выполнить операцию. Пожалуйста, попробуйте позже',
      'T10': 'Ok',
      'T11': 'Заблокирован',
      'T12': 'Блокировать ',
    },
    'german': {
      'T00': 'Profil',
      'T01': 'Blockierung',
      'T02': 'Entsperren',
      'T03': 'Blockieren ',
      'T04': 'Entsperren ',
      'T05': 'Stornieren',
      'T06': 'Ja',
      'T07': 'Der Benutzer ist entsperrt und kann auf Ihre Karte zugreifen',
      'T08': 'Der Benutzer ist gesperrt und hat bis zur Freigabe keinen Zugriff mehr auf Ihre Karte',
      'T09': 'Ein Fehler ist aufgetreten. Operation konnte nicht ausgeführt werden. Bitte versuchen Sie es später noch einmal',
      'T10': 'Ok',
      'T11': 'Blockiert',
      'T12': 'Block ',
    },
    'japanese': {
      'T00': 'プロフィール',
      'T01': 'ブロッキング',
      'T02': 'ブロックを解除する',
      'T03': 'をブロックしますか ',
      'T04': 'のブロックを解除しますか ',
      'T05': 'キャンセル',
      'T06': 'はい',
      'T07': 'ユーザーはブロックが解除され、カードにアクセスできます',
      'T08': 'ユーザーはブロックされ、ブロックが解除されるまでカードにアクセスできなくなります',
      'T09': 'エラーが発生しました。 操作を実行できませんでした。 後でもう一度やり直してください',
      'T10': 'Ok',
      'T11': 'ブロックされた',
      'T12': 'ブロック ',
    },
    'italian': {
      'T00': 'Profilo',
      'T01': 'Blocco',
      'T02': 'Sblocco',
      'T03': 'Vuoi davvero bloccare l\'accesso alla tua carta per ',
      'T04': 'Sbloccare ',
      'T05': 'Annulla',
      'T06': 'Sì',
      'T07': 'L\'utente è sbloccato e può accedere alla tua carta',
      'T08': 'L\'utente è bloccato e non ha più accesso alla tua carta finché non viene sbloccato',
      'T09': 'Si è verificato un errore. Impossibile eseguire l\'operazione. Per favore riprova più tardi',
      'T10': 'Ok',
      'T11': 'Bloccato',
      'T12': 'Bloccare ',
    },
    'french': {
      'T00': 'Profil',
      'T01': 'Blocage',
      'T02': 'Déblocage',
      'T03': 'Voulez-vous vraiment bloquer l\'accès à votre carte pendant ',
      'T04': 'Débloquer ',
      'T05': 'Annuler',
      'T06': 'Oui',
      'T07': 'L\'utilisateur est débloqué et peut accéder à votre carte',
      'T08': 'L\'utilisateur est bloqué et n\'a plus accès à votre carte jusqu\'à ce qu\'il soit débloqué',
      'T09': 'Une erreur s\'est produite. Impossible d\'effectuer l\'opération. Veuillez réessayer plus tard',
      'T10': 'Ok',
      'T11': 'Bloqué',
      'T12': 'Bloquer ',
    },
    'spanish': {
      'T00': 'Perfil',
      'T01': 'Bloqueo',
      'T02': 'Desbloqueo',
      'T03': '¿Realmente desea bloquear el acceso a su tarjeta para ',
      'T04': 'Desatascar ',
      'T05': 'Cancelar',
      'T06': 'Si',
      'T07': 'El usuario está desbloqueado y puede acceder a su tarjeta',
      'T08': 'El usuario está bloqueado y ya no tendrá acceso a su tarjeta hasta que se desbloquee',
      'T09': 'Un error ha ocurrido. No se pudo realizar la operación. Por favor, inténtelo de nuevo más tarde',
      'T10': 'Ok',
      'T11': 'Obstruido',
      'T12': 'Bloquear ',
    },
    'korean': {
      'T00': '프로필',
      'T01': '블로킹',
      'T02': '차단 해제',
      'T03': '카드에 대한 액세스를 정말로 차단 하시겠습니까? ',
      'T04': '차단 해제 ',
      'T05': '취소',
      'T06': '예',
      'T07': '사용자가 차단 해제되어 카드에 액세스 할 수 있습니다',
      'T08': '사용자가 차단되고 차단 해제 될 때까지 더 이상 카드에 액세스 할 수 없습니다',
      'T09': '오류가 발생했습니다. 작업을 수행 할 수 없습니다. 나중에 다시 시도하십시오',
      'T10': 'Ok',
      'T11': '막힌',
      'T12': '블록 ',
    },
  };
}