class TextAddingCard {

  final Map<String, Map<String, String>> strings = {
    'english': {
      'T00': 'Card added successfully',
      'T01': 'Ок',
      'T02': 'Could not add card',
      'T03': 'Please check internet connection or try again later',
      'T04': 'Back',
      'T05': 'Retry',
      'T06': 'Save',
      'T07': 'Maximum number of cards that can be added to collection is - ',
    },
    'russian': {
      'T00': 'Карточка успешно добавлена',
      'T01': 'Ок',
      'T02': 'Не удалось добавить карточку',
      'T03': 'Пожалуйста, проверьте подключение к интернету или попробуйте еще раз позднее',
      'T04': 'Назад',
      'T05': 'Повтор',
      'T06': 'Сохранить',
      'T07': 'Максимальное количество карт, которые можно добавить в коллекцию - ',
    },
    'german': {
      'T00': 'Karte erfolgreich hinzugefügt',
      'T01': 'Ок',
      'T02': 'Karte konnte nicht hinzugefügt werden',
      'T03': 'Bitte überprüfen Sie die Internetverbindung oder versuchen Sie es später erneut',
      'T04': 'Zurück',
      'T05': 'Wiederholen',
      'T06': 'Speichern',
      'T07': 'Die maximale Anzahl von Karten, die zur Sammlung hinzugefügt werden können, beträgt - ',
    },
    'japanese': {
      'T00': 'カードが正常に追加されました',
      'T01': 'Ok',
      'T02': 'カードを追加できませんでした',
      'T03': 'インターネット接続を確認するか、後でもう一度お試しください',
      'T04': '後ろへ',
      'T05': 'リトライ',
      'T06': '保存する',
      'T07': 'コレクションに追加できるカードの最大数は - ',
    },
    'italian': {
      'T00': 'Carta aggiunta con successo',
      'T01': 'Ок',
      'T02': 'Impossibile aggiungere la carta',
      'T03': 'Verifica la connessione a Internet o riprova più tardi',
      'T04': 'Indietro',
      'T05': 'Riprova',
      'T06': 'Salva',
      'T07': 'Il numero massimo di carte che possono essere aggiunte alla raccolta è - ',
    },
    'french': {
      'T00': 'Carte ajoutée avec succès',
      'T01': 'Ок',
      'T02': 'Impossible d\'ajouter la carte',
      'T03': 'Veuillez vérifier la connexion Internet ou réessayer plus tard',
      'T04': 'Retour',
      'T05': 'Réessayez',
      'T06': 'Enregistrer',
      'T07': 'Le nombre maximum de cartes pouvant être ajoutées à la collection est - ',
    },
    'spanish': {
      'T00': 'Tarjeta agregada correctamente',
      'T01': 'Ок',
      'T02': 'No se pudo agregar la tarjeta',
      'T03': 'Comprueba la conexión a Internet o vuelve a intentarlo más tarde',
      'T04': 'Regreso',
      'T05': 'Rever',
      'T06': 'Salvar',
      'T07': 'La cantidad máxima de tarjetas que se pueden agregar a la colección es - ',
    },
    'korean': {
      'T00': '카드가 성공적으로 추가되었습니다',
      'T01': 'Ок',
      'T02': '카드를 추가 할 수 없습니다',
      'T03': '인터넷 연결을 확인하거나 나중에 다시 시도하십시오',
      'T04': '뒤',
      'T05': '다시 해 보다',
      'T06': '저장',
      'T07': '컬렉션에 추가 할 수있는 최대 카드 수는 - ',
    },
  };

}