class TextHomePageMain {

  final Map<String, Map<String, String>> strings = {
    'english': {
      'T00': 'Main',
      'T01': 'Awaiting: ',
      'T02': 'Create new',
      'T03': 'Create new card',
      'T04': 'Maximum number of cards that can be created is - ',
      'T05': 'Ok',
      'T06': 'Add',
      'T07': 'Share',
      'T08': 'Maximum number of cards that can be added to collection is - ',
    },
    'russian': {
      'T00': 'Главная',
      'T01': 'Ожидают: ',
      'T02': 'Создать новую',
      'T03': 'Создайте новую карту',
      'T04': 'Максимальное количество карточек, которое можно создать - ',
      'T05': 'Ok',
      'T06': 'Добавить',
      'T07': 'Поделиться',
      'T08': 'Максимальное количество карт, которые можно добавить в коллекцию - ',
    },
    'german': {
      'T00': 'Main',
      'T01': 'Warten: ',
      'T02': 'Erstelle neu',
      'T03': 'Neue Karte erstellen',
      'T04': 'Die maximale Anzahl von Karten, die erstellt werden können, beträgt - ',
      'T05': 'Ok',
      'T06': 'Hinzufügen',
      'T07': 'Teilen',
      'T08': 'Die maximale Anzahl von Karten, die zur Sammlung hinzugefügt werden können, beträgt - ',
    },
    'japanese': {
      'T00': 'メイン',
      'T01': '待っています: ',
      'T02': '新しく作る',
      'T03': '新しいカードを作成する',
      'T04': '作成できるカードの最大数は - ',
      'T05': 'Ok',
      'T06': '追加',
      'T07': 'シェア',
      'T08': 'コレクションに追加できるカードの最大数は - ',
    },
    'italian': {
      'T00': 'Principale',
      'T01': 'Inattesa: ',
      'T02': 'Creare nuovo',
      'T03': 'Crea nuova carta',
      'T04': 'Il numero massimo di carte che è possibile creare è - ',
      'T05': 'Ok',
      'T06': 'Inserisci',
      'T07': 'Condividere',
      'T08': 'Il numero massimo di carte che possono essere aggiunte alla raccolta è - ',
    },
    'french': {
      'T00': 'Principal',
      'T01': 'En attente: ',
      'T02': 'Créer un nouveau',
      'T03': 'Créer une nouvelle carte',
      'T04': 'Le nombre maximum de cartes pouvant être créées est de - ',
      'T05': 'Ok',
      'T06': 'Ajouter',
      'T07': 'Partager',
      'T08': 'Le nombre maximum de cartes pouvant être ajoutées à la collection est - ',
    },
    'spanish': {
      'T00': 'Principal',
      'T01': 'Esperando: ',
      'T02': 'Crear nueva',
      'T03': 'Crear nueva tarjeta',
      'T04': 'La cantidad máxima de tarjetas que se pueden crear es - ',
      'T05': 'Ok',
      'T06': 'Añadir',
      'T07': 'Compartir',
      'T08': 'La cantidad máxima de tarjetas que se pueden agregar a la colección es - ',
    },
    'korean': {
      'T00': '본관',
      'T01': '대기 중 : ',
      'T02': '새로 만들기',
      'T03': '새 카드 만들기',
      'T04': '생성 할 수있는 최대 카드 수는 - ',
      'T05': 'Ok',
      'T06': '더하다',
      'T07': '공유',
      'T08': '컬렉션에 추가 할 수있는 최대 카드 수는 - ',
    },
  };

}